HLA-A*01:01: 0
HLA-A*02:01: 1
HLA-A*02:05: 14
HLA-A*02:06: 24
HLA-A*03:01: 2
HLA-A*11:01: 3
HLA-A*24:02: 6
HLA-A*29:02: 15
HLA-A*30:02: 13
HLA-A*68:01: 7
HLA-B*07:02: 5
HLA-B*08:01: 10
HLA-B*15:01: 4
HLA-B*18:01: 18
HLA-B*27:05: 11
HLA-B*27:09: 20
HLA-B*35:01: 21
HLA-B*35:03: 29
HLA-B*35:08: 32
HLA-B*37:01: 9
HLA-B*38:01: 30
HLA-B*39:01: 36
HLA-B*40:01: 22
HLA-B*41:02: 34
HLA-B*44:02: 25
HLA-B*44:03: 38
HLA-B*44:05: 37
HLA-B*50:01: 16
HLA-B*51:01: 19
HLA-B*57:01: 8
HLA-B*57:03: 26
HLA-C*01:02: 23
HLA-C*03:03: 35
HLA-C*03:04: 28
HLA-C*04:01: 39
HLA-C*05:01: 17
HLA-C*06:02: 41
HLA-C*07:01: 31
HLA-C*07:02: 40
HLA-C*08:02: 12
HLA-C*12:02: 27
HLA-C*14:02: 33
unknown: 43