TRAJ10*01: 50
TRAJ11*01: 44
TRAJ12*01: 19
TRAJ13*01: 8
TRAJ13*02: 51
TRAJ15*01: 36
TRAJ16*01: 41
TRAJ17*01: 28
TRAJ18*01: 46
TRAJ2*01: 61
TRAJ20*01: 10
TRAJ21*01: 43
TRAJ22*01: 6
TRAJ23*01: 15
TRAJ23*02: 52
TRAJ24*01: 11
TRAJ24*02: 53
TRAJ24*03: 64
TRAJ25*01: 57
TRAJ26*01: 31
TRAJ27*01: 14
TRAJ28*01: 47
TRAJ29*01: 25
TRAJ3*01: 21
TRAJ30*01: 9
TRAJ31*01: 18
TRAJ32*01: 35
TRAJ32*02: 55
TRAJ33*01: 33
TRAJ34*01: 20
TRAJ35*01: 37
TRAJ36*01: 48
TRAJ37*01: 5
TRAJ37*02: 58
TRAJ38*01: 40
TRAJ39*01: 13
TRAJ4*01: 34
TRAJ40*01: 30
TRAJ41*01: 16
TRAJ42*01: 3
TRAJ43*01: 32
TRAJ44*01: 45
TRAJ45*01: 1
TRAJ46*01: 54
TRAJ47*01: 49
TRAJ47*02: 56
TRAJ48*01: 4
TRAJ49*01: 7
TRAJ5*01: 29
TRAJ50*01: 27
TRAJ52*01: 12
TRAJ53*01: 26
TRAJ54*01: 38
TRAJ56*01: 17
TRAJ57*01: 24
TRAJ58*01: 39
TRAJ6*01: 0
TRAJ7*01: 42
TRAJ8*01: 23
TRAJ9*01: 22
TRDJ1*01: 59
TRDJ2*01: 63
TRDJ3*01: 62
TRDJ4*01: 60
unknown: 2
