TRBJ1-1*01: 5
TRBJ1-2*01: 4
TRBJ1-3*01: 13
TRBJ1-4*01: 1
TRBJ1-5*01: 7
TRBJ1-6*01: 12
TRBJ1-6*02: 14
TRBJ2-1*01: 0
TRBJ2-2*01: 11
TRBJ2-3*01: 6
TRBJ2-4*01: 9
TRBJ2-5*01: 8
TRBJ2-6*01: 10
TRBJ2-7*01: 3
TRGJP2*01: 15
unknown: 2
