TRAV1-1*01: 43
TRAV1-2*01: 42
TRAV10*01: 54
TRAV12-1*01: 15
TRAV12-2*01: 2
TRAV12-2*02: 3
TRAV12-3*01: 13
TRAV13-1*01: 5
TRAV13-1*02: 6
TRAV13-2*01: 14
TRAV14/DV4*01: 36
TRAV14/DV4*02: 38
TRAV14/DV4*03: 37
TRAV16*01: 60
TRAV17*01: 44
TRAV18*01: 28
TRAV19*01: 35
TRAV2*01: 53
TRAV20*01: 50
TRAV20*02: 51
TRAV21*01: 4
TRAV22*01: 8
TRAV23/DV6*01: 18
TRAV24*01: 23
TRAV25*01: 46
TRAV26-1*01: 32
TRAV26-1*02: 33
TRAV26-2*01: 34
TRAV27*01: 30
TRAV27*03: 31
TRAV29/DV5*01: 16
TRAV29/DV5*02: 17
TRAV3*01: 52
TRAV30*01: 9
TRAV34*01: 10
TRAV35*01: 22
TRAV35*02: 21
TRAV36/DV7*01: 56
TRAV36/DV7*02: 11
TRAV38-1*01: 39
TRAV38-1*03: 41
TRAV38-2/DV8*01: 40
TRAV39*01: 48
TRAV4*01: 12
TRAV40*01: 29
TRAV41*01: 49
TRAV5*01: 7
TRAV6*01: 19
TRAV6*02: 20
TRAV7*01: 55
TRAV8-1*01: 59
TRAV8-2*01: 27
TRAV8-3*01: 57
TRAV8-3*02: 58
TRAV8-4*01: 24
TRAV8-6*01: 25
TRAV8-6*02: 26
TRAV9-1*01: 47
TRAV9-2*01: 0
TRAV9-2*02: 1
TRDV1*01: 45
unknown: 62