TRBV10-1*01: 42
TRBV10-1*02: 62
TRBV10-2*01: 8
TRBV10-3*01: 30
TRBV10-3*02: 53
TRBV11-1*01: 39
TRBV11-2*01: 4
TRBV11-2*02: 54
TRBV11-3*01: 45
TRBV12-3*01: 3
TRBV12-4*01: 44
TRBV12-5*01: 23
TRBV13*01: 34
TRBV13*02: 59
TRBV14*01: 16
TRBV15*01: 35
TRBV15*02: 51
TRBV16*01: 27
TRBV18*01: 15
TRBV19*01: 10
TRBV19*02: 13
TRBV19*03: 68
TRBV2*01: 1
TRBV2*03: 58
TRBV20-1*01: 5
TRBV20/OR9-2*01: 52
TRBV23-1*01: 63
TRBV24-1*01: 38
TRBV25-1*01: 22
TRBV27*01: 2
TRBV28*01: 12
TRBV29-1*01: 18
TRBV3-1*01: 26
TRBV30*01: 37
TRBV30*02: 48
TRBV4-1*01: 25
TRBV4-2*01: 28
TRBV4-3*01: 21
TRBV5-1*01: 9
TRBV5-3*01: 66
TRBV5-4*01: 24
TRBV5-4*02: 65
TRBV5-5*01: 17
TRBV5-6*01: 20
TRBV5-7*01: 55
TRBV5-8*01: 33
TRBV6-1*01: 31
TRBV6-2*01: 19
TRBV6-3*01: 49
TRBV6-4*01: 41
TRBV6-4*02: 60
TRBV6-5*01: 14
TRBV6-6*01: 40
TRBV6-6*02: 50
TRBV6-7*01: 67
TRBV6-8*01: 57
TRBV7-1*01: 36
TRBV7-2*01: 7
TRBV7-2*02: 29
TRBV7-3*01: 47
TRBV7-4*01: 61
TRBV7-6*01: 6
TRBV7-7*01: 46
TRBV7-8*01: 32
TRBV7-9*01: 11
TRBV7-9*03: 43
TRBV9*01: 0
TRBV9*02: 56
TRGV8*01: 64
unknown: 70